export const pages = [
  ["main_image", "商品主图"],
  ["detail_page", "详情页"],
  ["ecommerce_poster", "电商套图"],
  ["translation", "图片翻译"],
  ["apparel:MODEL_REPLACE", "模特替换"],
  ["apparel:FACE_SWAP", "模特换脸"],
  ["apparel:BACKGROUND_REPLACE", "背景替换"],
  ["apparel:FACE_BACKGROUND_SWAP", "换脸换背景"],
  ["apparel:MODEL_TRY_ON", "模特试穿"],
  ["apparel:APPAREL_TRY_ON", "服装上身"],
  ["apparel:MULTI_GARMENT", "多件换衣"],
  ["apparel:DUAL_MODEL_GARMENT", "双人换衣"],
  ["apparel:SHOES_TRY_ON", "鞋靴试穿"],
  ["apparel:ACCESSORY_TRY_ON", "配饰试戴"],
  ["video:TEXT_TO_VIDEO", "文生视频"],
  ["video:FIRST_FRAME_TO_VIDEO", "首帧视频"],
  ["video:PRODUCT_REPLACE", "视频商品替换"],
  ["video:MODEL_SELLING", "模特带货"],
  ["video:PRODUCT_REPLACEMENT", "视频商品置换"],
  ["aigc", "AIGC 画布"],
] as const;
export const examples = [
  {
    id: "models",
    label: "查询主图模型",
    method: "GET",
    path: "/open/models",
    params: {
      capability: "main_image",
      configKey: "main_image",
      feature: "MAIN_IMAGE",
    },
  },
  {
    id: "videoModels",
    label: "查询文生视频模型",
    method: "GET",
    path: "/open/models",
    params: {
      capability: "video:TEXT_TO_VIDEO",
      configKey: "video_tool_text_to_video",
    },
  },
  {
    id: "apparelConfig",
    label: "查询背景替换配置",
    method: "GET",
    path: "/open/apparel-workflows/configuration",
    params: { workflowType: "BACKGROUND_REPLACE" },
  },
  {
    id: "design",
    label: "创建首图生成",
    method: "POST",
    path: "/open/design-jobs",
    params: {
      clientRequestId: "",
      feature: "MAIN_IMAGE",
      modelId: "",
      parameterSchemaVersion: "",
      ratio: "1:1",
      outputCount: 1,
      language: "zh-CN",
      contentLanguage: "zh-CN",
      platform: "TAOBAO",
      sourceRoles: ["PRODUCT_MAIN"],
      sourceAssetIds: [],
      spec: {
        kind: "MAIN_IMAGE",
        productDescription: "为图中的商品生成一张简洁清晰的电商主图",
      },
      context: { example: "sdk-demo" },
    },
  },
  {
    id: "apparel",
    label: "创建服装背景替换",
    method: "POST",
    path: "/open/apparel-workflows",
    params: {
      clientRequestId: "",
      workflowType: "BACKGROUND_REPLACE",
      configurationVersion: 0,
      prompt: "保留图一人物，替换为图二背景，保持自然光影",
      ratio: "1:1",
      outputCount: 1,
      materials: [
        { role: "BASE_PERSON", assetId: "" },
        { role: "BACKGROUND", assetId: "" },
      ],
      context: { example: "sdk-demo" },
    },
  },
  {
    id: "video",
    label: "创建文生视频",
    method: "POST",
    path: "/open/video-workflows",
    params: {
      clientRequestId: "",
      workflowType: "TEXT_TO_VIDEO",
      prompt: "阳光下的森林，镜头缓慢向前移动",
      modelId: "",
      parameterSchemaVersion: "",
      platform: "TAOBAO",
      contentLanguage: "NONE",
      language: "zh-CN",
      ratio: "16:9",
      resolution: "",
      duration: "",
      materials: [],
      context: { example: "sdk-demo" },
    },
  },
  {
    id: "submission",
    label: "查询首图受理状态",
    method: "GET",
    path: "/open/design-jobs/submissions/{submissionNo}",
    params: { submissionNo: "" },
  },
  {
    id: "apparelSubmission",
    label: "查询服装受理状态",
    method: "GET",
    path: "/open/apparel-workflows/submissions/{submissionNo}",
    params: { submissionNo: "" },
  },
  {
    id: "videoSubmission",
    label: "查询视频受理状态",
    method: "GET",
    path: "/open/video-workflows/submissions/{submissionNo}",
    params: { submissionNo: "" },
  },
  {
    id: "generation",
    label: "查询最终结果与结算",
    method: "GET",
    path: "/open/generations/{submissionNo}",
    params: { submissionNo: "" },
  },
  {
    id: "history",
    label: "查询统一历史",
    method: "GET",
    path: "/open/history",
    params: {},
  },
] as const;
